version: '3.7'

services:
  backend:
    build:
      context: ./backend/develop
      dockerfile: Dockerfile
    # container_name: golang_backend
    environment:
      - GOPATH=/app/go-space
    restart: unless-stopped
    tty: true
    stdin_open: true
    working_dir: /app
    # volumes:
    #   - ./backend/develop/go-space:/app/go-space/
    #   - ./backend/develop/mlm-ng-goapi:/app/go-space/src/mlm-ng-goapi
    #   - ./backend/develop/mlm-ng-goapi:/app/go-space/src/github.com/smartblock/mlm-ng-goapi
    ports:
      - '8000:8000'
    # depends_on:
    #   - database
    network_mode: "host"
